import { Card } from "./card";

/** Replace card of `soughtId` in given `cards` with new card generated by `replacerFn`.  Returns _copy_ of original cards.*/
export function replaceCard(
    cards: Card[],
    soughtId: number,
    replacerFn: (c: Card) => Card
): Card[] {
    function getAllIds(cards: Card[]): number[] {
        return cards.map((c) => c.id);
    }

    const newArray = [...cards];
    const ix = newArray.findIndex((c) => c.id === soughtId);
    if (ix === -1) {
        throw new Error(`Missing card ${soughtId} in ${getAllIds(cards)}`);
    }
    newArray[ix] = replacerFn(newArray[ix]);
    return newArray;
}
